apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260516-004629-1uw80thcknj7-service
spec:
  selector:
    app: enterprise-system-20260516-004629-1uw80thcknj7
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
